# Koco Dataset

Koco dataset was built as a part of a research paper BEEP! Korean Corpus of Online News Comments for Toxic Speech Detection (Moon et al., SocialNLP 2020). The report and the Github could be found below.

- Research Paper: https://aclanthology.org/2020.socialnlp-1.4/
- Github: https://github.com/kocohub/korean-hate-speech

### Import necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Train dataset

In [3]:
import koco

train_dev = koco.load_dataset('korean-hate-speech', mode='train_dev')

In [4]:
train_dev.keys()

dict_keys(['train', 'dev'])

In [5]:
train_dev['train'][:5] # Train set top 5 rows

[{'comments': '(현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속 추모받네....',
  'contain_gender_bias': False,
  'bias': 'others',
  'hate': 'hate',
  'news_title': '"밤새 조문 행렬…故 전미선, 동료들이 그리워하는 따뜻한 배우 [종합]"'},
 {'comments': '....한국적인 미인의 대표적인 분...너무나 곱고아름다운모습...그모습뒤의 슬픔을 미처 알지못했네요ㅠ',
  'contain_gender_bias': False,
  'bias': 'none',
  'hate': 'none',
  'news_title': '"\'연중\' 故 전미선, 생전 마지막 미공개 인터뷰…환하게 웃는 모습 \'먹먹\'[종합]"'},
 {'comments': '...못된 넘들...남의 고통을 즐겼던 넘들..이젠 마땅한 처벌을 받아야지..,그래야, 공정한 사회지...심은대로 거두거라...',
  'contain_gender_bias': False,
  'bias': 'none',
  'hate': 'hate',
  'news_title': '"[단독] 잔나비, 라디오 출연 취소→\'한밤\' 방송 연기..비판 여론 ing(종합)"'},
 {'comments': '1,2화 어설펐는데 3,4화 지나서부터는 갈수록 너무 재밌던데',
  'contain_gender_bias': False,
  'bias': 'none',
  'hate': 'none',
  'news_title': '"\'아스달 연대기\' 장동건-김옥빈, 들끓는 \'욕망커플\'→눈물범벅 \'칼끝 대립\'"'},
 {'comments': '1. 사람 얼굴 손톱으로 긁은것은 인격살해이고2. 동영상이 몰카냐? 메걸리안들 생각이 없노',
  'contain_gender_bias': True,
  'bias': 'gender',
  'hate': 'hate',
  'news_title': '[DA:이슈] ‘구하라 비보’ 최종범 항소심에 영향?…법조계 “‘공소권 없음’ 아냐”'}]

In [ ]:
df_train = pd.DataFrame(train_dev['train']) # Convert it yo pandas
df_train.head()

,comments,contain_gender_bias,bias,hate,news_title
0,(현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속...,False,others,hate,"""밤새 조문 행렬…故 전미선, 동료들이 그리워하는 따뜻한 배우 [종합]"""
1,....한국적인 미인의 대표적인 분...너무나 곱고아름다운모습...그모습뒤의 슬픔을...,False,none,none,"""'연중' 故 전미선, 생전 마지막 미공개 인터뷰…환하게 웃는 모습 '먹먹'[종합]"""
2,"...못된 넘들...남의 고통을 즐겼던 넘들..이젠 마땅한 처벌을 받아야지..,그래...",False,none,hate,"""[단독] 잔나비, 라디오 출연 취소→'한밤' 방송 연기..비판 여론 ing(종합)"""
3,"1,2화 어설펐는데 3,4화 지나서부터는 갈수록 너무 재밌던데",False,none,none,"""'아스달 연대기' 장동건-김옥빈, 들끓는 '욕망커플'→눈물범벅 '칼끝 대립'"""
4,1. 사람 얼굴 손톱으로 긁은것은 인격살해이고2. 동영상이 몰카냐? 메걸리안들 생각...,True,gender,hate,[DA:이슈] ‘구하라 비보’ 최종범 항소심에 영향?…법조계 “‘공소권 없음’ 아냐”

In [7]:
df_train.describe()

,comments,contain_gender_bias,bias,hate,news_title
count,7896,7896,7896,7896,7896
unique,7896,2,3,3,1478
top,(현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속...,False,none,none,"""'같이 살래요' 유동근, 장미희에 """"해아 물산 며느리, 내 딸이다"""""""
freq,1,6664,5148,3486,13

In [8]:
df_train.shape

(7896, 5)

Train set has 7896 rows

In [9]:
df_train_10 = df_train[:10]
df_train_10

,comments,contain_gender_bias,bias,hate,news_title
0,(현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속...,False,others,hate,"""밤새 조문 행렬…故 전미선, 동료들이 그리워하는 따뜻한 배우 [종합]"""
1,....한국적인 미인의 대표적인 분...너무나 곱고아름다운모습...그모습뒤의 슬픔을...,False,none,none,"""'연중' 故 전미선, 생전 마지막 미공개 인터뷰…환하게 웃는 모습 '먹먹'[종합]"""
2,"...못된 넘들...남의 고통을 즐겼던 넘들..이젠 마땅한 처벌을 받아야지..,그래...",False,none,hate,"""[단독] 잔나비, 라디오 출연 취소→'한밤' 방송 연기..비판 여론 ing(종합)"""
3,"1,2화 어설펐는데 3,4화 지나서부터는 갈수록 너무 재밌던데",False,none,none,"""'아스달 연대기' 장동건-김옥빈, 들끓는 '욕망커플'→눈물범벅 '칼끝 대립'"""
4,1. 사람 얼굴 손톱으로 긁은것은 인격살해이고2. 동영상이 몰카냐? 메걸리안들 생각...,True,gender,hate,[DA:이슈] ‘구하라 비보’ 최종범 항소심에 영향?…법조계 “‘공소권 없음’ 아냐”
5,10+8 진짜 이승기랑 비교된다,False,none,none,"""[공식입장] '1박2일' 측 """"정준영 출연 중단 결정…심각성 고려"""""""
6,"100년안에 남녀간 성전쟁 한번 크게 치룬 후 일부다처제, 여성의 정치참여 금지, ...",True,gender,hate,"""배우 마크 월버그, 성차별 논란에 출연료 16억원 전액 기부"""
7,10년뒤 윤서인은 분명히 재평가될것임. 말하나하나가 틀린게없음,False,none,none,"""[Oh!쎈 초점] """"정우성 공개 저격"""" 윤서인, 이쯤 되면 정우성 안티?"""
8,10년만에 재미를 느끼는 프로였는데왜 니들때문에 폐지를해야되냐,False,none,offensive,"""""""故설리 부재 하에 지속 어려워""""…'악플의밤' 측이 폐지를 결정한 이유 [종합]"""
9,10년차방탄팬인데 우리방탄처럼 성공은못하겠지만 일단 방탄의 부하가되고싶다는거니 이름...,False,none,offensive,"""""""'프듀2' 출신 합류"""" 느와르 """"롤모델 방탄소년단""""(종합)"""

In [10]:
df_dev = pd.DataFrame(train_dev['dev'])
df_dev.head()

,comments,contain_gender_bias,bias,hate,news_title
0,송중기 시대극은 믿고본다. 첫회 신선하고 좋았다.,False,none,none,"""'아스달 연대기' 뇌안탈 후계자 송중기, 이아르크에 숨어들었다 [종합]"""
1,지현우 나쁜놈,False,none,offensive,‘섹션TV’ 유인나 “결혼은 3년 후쯤 했으면…노력해보겠다”
2,알바쓰고많이만들면되지 돈욕심없으면골목식당왜나온겨 기댕기게나하고 산에가서팔어라,False,none,hate,"""'골목식당' 포방터시장, 계속되는 논란의 중심[SS초점]"""
3,설마 ㅈ 현정 작가 아니지??,True,gender,hate,"""""""마음 고생""""…나영석·정유미, 황당 불륜 지라시→방송작가 검거→벌금형 선고 [..."
4,이미자씨 송혜교씨 돈이 그리 많으면 탈세말고 그돈으로 평소에 불우이웃에게 기부도 좀...,False,none,offensive,"""이미자 탈세, 10년간 44억 넘는 소득 신고 누락…약 20억 세금 추가 납부"""

### Unlabeled Dataset

In [11]:
unlabeled = koco.load_dataset('korean-hate-speech', mode='unlabeled')

In [12]:
type(unlabeled)

list

In [13]:
unlabeled[34]

{'comments': '이주연 이쁜데왜~~~ 결혼까지해라 태양처럼',
 'news_title': '"[단독] 지드래곤♥이주연, 제주도 데이트…2018년 1호 커플 탄생"'}

### Test Dataset

In [14]:
test = koco.load_dataset('korean-hate-speech', mode='test')

In [15]:
type(test)

list

In [16]:
test[33]

{'comments': '끝낼때도 됐지 요즘같은 분위기엔 성드립 잘못쳤다가 난리. 그동안 잘봤습니다',
 'news_title': '[단독] ‘SNL 코리아’ 공식적인 폐지 확정…아름다운 종료'}

### Google Translation API

In [17]:
import os
import requests
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")
print("Key loaded:", API_KEY is not None)

Key loaded: True

In [18]:
URL = "https://translation.googleapis.com/language/translate/v2"

def translate_google(text, target_language="en", source_language="ko"):
    """
    Function for translating text using Google Translation API
    """

    # If the text is empty, return the text
    if pd.isna(text) or str(text).strip() == "":
        return text

    # Set the parameters
    params = {
        "q": text,
        "target": target_language,
        "source": source_language,
        "key": API_KEY
    }
    response = requests.post(URL, data=params)

    if response.status_code != 200:
        print(f"Error translating: {text[:50]}... -> {response.text}")
        return None

    result = response.json()
    return result["data"]["translations"][0]["translatedText"]

df_train_10['comments_trans_g_en'] = df_train_10['comments'].apply(lambda x: translate_google(x))
df_train_10['title_trans_g_en'] = df_train_10['news_title'].apply(lambda x: translate_google(x))

/var/folders/8j/bfss3njx263_tq3r6hcj4nl80000gn/T/ipykernel_84837/7080885.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train_10['comments_trans_g_en'] = df_train_10['comments'].apply(lambda x: translate_google(x))
/var/folders/8j/bfss3njx263_tq3r6hcj4nl80000gn/T/ipykernel_84837/7080885.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train_10['title_trans_g_en'] = df_train_10['news_title'].apply(lambda x: translate_google(x))

In [19]:
pd.set_option('display.max_colwidth', None)  # no limit

df_train_10

,comments,contain_gender_bias,bias,hate,news_title,comments_trans_g_en,title_trans_g_en
0,(현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속 추모받네....,False,others,hate,"""밤새 조문 행렬…故 전미선, 동료들이 그리워하는 따뜻한 배우 [종합]""","(The hotel owner&#39;s current feelings) Ah, damn it, I got struck by a bolt from the blue and my hotel is about to go bankrupt, but someone else keeps getting mourned....","&quot;Way of mourners overnight... The late Jeon Mi-seon, a warm actress missed by her colleagues [Roundup]&quot;"
1,....한국적인 미인의 대표적인 분...너무나 곱고아름다운모습...그모습뒤의 슬픔을 미처 알지못했네요ㅠ,False,none,none,"""'연중' 故 전미선, 생전 마지막 미공개 인터뷰…환하게 웃는 모습 '먹먹'[종합]""",....A representative figure of quintessential Korean beauty... Such a graceful and lovely appearance... I never realized the sadness behind it.,"&quot;&#39;Yeonjung&#39; The late Jeon Mi-seon, last unreleased interview before her death... Her bright smile leaves a heavy heart [Roundup]&quot;"
2,"...못된 넘들...남의 고통을 즐겼던 넘들..이젠 마땅한 처벌을 받아야지..,그래야, 공정한 사회지...심은대로 거두거라...",False,none,hate,"""[단독] 잔나비, 라디오 출연 취소→'한밤' 방송 연기..비판 여론 ing(종합)""",...You wicked bastards... You who reveled in the suffering of others... Now you deserve the punishment you deserve... That is the only way to have a just society... You reap what you sow...,&quot;[Exclusive] Jannabi Cancels Radio Appearance → Postpones &#39;Midnight&#39; Broadcast... Criticism Continues (Roundup)&quot;
3,"1,2화 어설펐는데 3,4화 지나서부터는 갈수록 너무 재밌던데",False,none,none,"""'아스달 연대기' 장동건-김옥빈, 들끓는 '욕망커플'→눈물범벅 '칼끝 대립'""","Episodes 1 and 2 were a bit clumsy, but after episodes 3 and 4, it got more and more fun.","&quot;&#39;Arthdal Chronicles&#39; Jang Dong-gun and Kim Ok-bin, from seething &#39;couple of desire&#39; to tear-soaked &#39;sword-edge confrontation&#39;&quot;"
4,1. 사람 얼굴 손톱으로 긁은것은 인격살해이고2. 동영상이 몰카냐? 메걸리안들 생각이 없노,True,gender,hate,[DA:이슈] ‘구하라 비보’ 최종범 항소심에 영향?…법조계 “‘공소권 없음’ 아냐”,"1. Scratching someone&#39;s face with fingernails is character assassination, and 2. Is the video a hidden camera recording? You Megalians have no common sense.",[DA:Issue] &#39;Goo Hara Tragedy&#39; to Impact Choi Jong-beom&#39;s Appeal?… Legal Community: &quot;Not &#39;No Right to Prosecute&#39;&quot;
5,10+8 진짜 이승기랑 비교된다,False,none,none,"""[공식입장] '1박2일' 측 """"정준영 출연 중단 결정…심각성 고려""""""",10+8 really compares to Lee Seung-gi.,&quot;[Official Statement] &#39;1 Night 2 Days&#39; Side: &quot;Decision to Suspend Jung Joon-young&#39;s Appearance... Considering the Seriousness&quot;
6,"100년안에 남녀간 성전쟁 한번 크게 치룬 후 일부다처제, 여성의 정치참여 금지, 여성 투표권 삭제가 세계의 공통문화로 자리잡을듯. 암탉이 너무 울어댐.",True,gender,hate,"""배우 마크 월버그, 성차별 논란에 출연료 16억원 전액 기부""","It seems that within 100 years, after a major gender war, polygamy, the ban on women&#39;s political participation, and the elimination of women&#39;s suffrage will become the common global culture. The hens are crowing too much.",Actor Mark Wahlberg Donates Entire 1.6 Billion Won Salary Amid Sexism Controversy
7,10년뒤 윤서인은 분명히 재평가될것임. 말하나하나가 틀린게없음,False,none,none,"""[Oh!쎈 초점] """"정우성 공개 저격"""" 윤서인, 이쯤 되면 정우성 안티?""",Yoon Seo-in will definitely be re-evaluated in 10 years. Every single word he says is correct.,"&quot;[Oh! Ssen Focus] &quot;Publicly attacking Jung Woo-sung&quot; Yoon Seo-in, at this point, is he an anti-fan of Jung Woo-sung?&quot;"
8,10년만에 재미를 느끼는 프로였는데왜 니들때문에 폐지를해야되냐,False,none,offensive,"""""""故설리 부재 하에 지속 어려워""""…'악플의밤' 측이 폐지를 결정한 이유 [종합]""","It was a show I enjoyed for the first time in 10 years, so why do we have to cancel it because of you guys?",&quot;Difficult to continue in the absence of the late Sulli&quot;… The reason &#39;Night of Malicious Comments&#39; decides to cancel [Roundup]
9,10년차방탄팬인데 우리방탄처럼 성공은못하겠지만 일단 방탄의 부하가되고싶다는거니 이름기억은해둠ㅇㅇ,False,none,offensive,"""""""'프듀2' 출신 합류"""" 느와르 """"롤모델 방탄소년단""""(종합)""","I&#39;ve been a BTS fan for 10 years. I know I won&#39;t be able to succeed like our BTS, but since you&#39;re saying you want to become their subordinate for now, I&#39;ll remember your name.",&quot;&quot;&quot;&#39;Produce 2&#39; alumni join&quot;&quot; Noir &quot;&quot;Role models BTS&quot;(Roundup)&quot;

In [20]:
import html
cols_to_clean = ["comments_trans_g_en", "title_trans_g_en"]

for c in cols_to_clean:
    df_train_10[c] = df_train_10[c].apply(lambda x: html.unescape(x) if pd.notna(x) else x)

/var/folders/8j/bfss3njx263_tq3r6hcj4nl80000gn/T/ipykernel_84837/3220947042.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train_10[c] = df_train_10[c].apply(lambda x: html.unescape(x) if pd.notna(x) else x)

In [21]:
df_train_10

,comments,contain_gender_bias,bias,hate,news_title,comments_trans_g_en,title_trans_g_en
0,(현재 호텔주인 심정) 아18 난 마른하늘에 날벼락맞고 호텔망하게생겼는데 누군 계속 추모받네....,False,others,hate,"""밤새 조문 행렬…故 전미선, 동료들이 그리워하는 따뜻한 배우 [종합]""","(The hotel owner's current feelings) Ah, damn it, I got struck by a bolt from the blue and my hotel is about to go bankrupt, but someone else keeps getting mourned....","""Way of mourners overnight... The late Jeon Mi-seon, a warm actress missed by her colleagues [Roundup]"""
1,....한국적인 미인의 대표적인 분...너무나 곱고아름다운모습...그모습뒤의 슬픔을 미처 알지못했네요ㅠ,False,none,none,"""'연중' 故 전미선, 생전 마지막 미공개 인터뷰…환하게 웃는 모습 '먹먹'[종합]""",....A representative figure of quintessential Korean beauty... Such a graceful and lovely appearance... I never realized the sadness behind it.,"""'Yeonjung' The late Jeon Mi-seon, last unreleased interview before her death... Her bright smile leaves a heavy heart [Roundup]"""
2,"...못된 넘들...남의 고통을 즐겼던 넘들..이젠 마땅한 처벌을 받아야지..,그래야, 공정한 사회지...심은대로 거두거라...",False,none,hate,"""[단독] 잔나비, 라디오 출연 취소→'한밤' 방송 연기..비판 여론 ing(종합)""",...You wicked bastards... You who reveled in the suffering of others... Now you deserve the punishment you deserve... That is the only way to have a just society... You reap what you sow...,"""[Exclusive] Jannabi Cancels Radio Appearance → Postpones 'Midnight' Broadcast... Criticism Continues (Roundup)"""
3,"1,2화 어설펐는데 3,4화 지나서부터는 갈수록 너무 재밌던데",False,none,none,"""'아스달 연대기' 장동건-김옥빈, 들끓는 '욕망커플'→눈물범벅 '칼끝 대립'""","Episodes 1 and 2 were a bit clumsy, but after episodes 3 and 4, it got more and more fun.","""'Arthdal Chronicles' Jang Dong-gun and Kim Ok-bin, from seething 'couple of desire' to tear-soaked 'sword-edge confrontation'"""
4,1. 사람 얼굴 손톱으로 긁은것은 인격살해이고2. 동영상이 몰카냐? 메걸리안들 생각이 없노,True,gender,hate,[DA:이슈] ‘구하라 비보’ 최종범 항소심에 영향?…법조계 “‘공소권 없음’ 아냐”,"1. Scratching someone's face with fingernails is character assassination, and 2. Is the video a hidden camera recording? You Megalians have no common sense.","[DA:Issue] 'Goo Hara Tragedy' to Impact Choi Jong-beom's Appeal?… Legal Community: ""Not 'No Right to Prosecute'"""
5,10+8 진짜 이승기랑 비교된다,False,none,none,"""[공식입장] '1박2일' 측 """"정준영 출연 중단 결정…심각성 고려""""""",10+8 really compares to Lee Seung-gi.,"""[Official Statement] '1 Night 2 Days' Side: ""Decision to Suspend Jung Joon-young's Appearance... Considering the Seriousness"""
6,"100년안에 남녀간 성전쟁 한번 크게 치룬 후 일부다처제, 여성의 정치참여 금지, 여성 투표권 삭제가 세계의 공통문화로 자리잡을듯. 암탉이 너무 울어댐.",True,gender,hate,"""배우 마크 월버그, 성차별 논란에 출연료 16억원 전액 기부""","It seems that within 100 years, after a major gender war, polygamy, the ban on women's political participation, and the elimination of women's suffrage will become the common global culture. The hens are crowing too much.",Actor Mark Wahlberg Donates Entire 1.6 Billion Won Salary Amid Sexism Controversy
7,10년뒤 윤서인은 분명히 재평가될것임. 말하나하나가 틀린게없음,False,none,none,"""[Oh!쎈 초점] """"정우성 공개 저격"""" 윤서인, 이쯤 되면 정우성 안티?""",Yoon Seo-in will definitely be re-evaluated in 10 years. Every single word he says is correct.,"""[Oh! Ssen Focus] ""Publicly attacking Jung Woo-sung"" Yoon Seo-in, at this point, is he an anti-fan of Jung Woo-sung?"""
8,10년만에 재미를 느끼는 프로였는데왜 니들때문에 폐지를해야되냐,False,none,offensive,"""""""故설리 부재 하에 지속 어려워""""…'악플의밤' 측이 폐지를 결정한 이유 [종합]""","It was a show I enjoyed for the first time in 10 years, so why do we have to cancel it because of you guys?","""Difficult to continue in the absence of the late Sulli""… The reason 'Night of Malicious Comments' decides to cancel [Roundup]"
9,10년차방탄팬인데 우리방탄처럼 성공은못하겠지만 일단 방탄의 부하가되고싶다는거니 이름기억은해둠ㅇㅇ,False,none,offensive,"""""""'프듀2' 출신 합류"""" 느와르 """"롤모델 방탄소년단""""(종합)""","I've been a BTS fan for 10 years. I know I won't be able to succeed like our BTS, but since you're saying you want to become their subordinate for now, I'll remember your name.","""""""'Produce 2' alumni join"""" Noir """"Role models BTS""(Roundup)"""

In [22]:
df_train_10.to_csv("df_train_10_g_trans.csv", index=False)

More cleaning needed. Above was done as a prework to see how Google translation works. Only translated the top 10 rows